app:
  log: debug
server:
  host: localhost
  port: 8001
  readTimeout:  5s
  writeTimeout: 10s
  idleTimeout:  120s
  certFile: ./assets/tls/cert.pem
  keyFile: ./assets/tls/key.pem
  shutdownTimeout: 10s
middleware:
  limiter:
    requestsPerSecond: 10000
    burst: 5
    timeToLive: 24h
    cleanupInterval: 1h
controller:
  maxNumberOfFiles: 1000
  maxFileSize: 2097152 # 2 MB
service:
  numberOfWorkersCalc: 8
  numberOfWorkersComp: 8
  albumIdLength: 8
  imageIdLength: 16
  tokenIdLength: 16
shortpixel:
  use: false
  url: https://api.shortpixel.com/v2/post-reducer.php
  url2: https://api.shortpixel.com/v2/reducer.php
  apiKey: abcdefghijklmnopqrst
  retry:
    times: 2
    pause: 10s
  wait: 30
  uploadTimeout: 30s
  downloadTimeout: 5s
  repeatIn: 10s
minio:
  use: false
  host: localhost
  port: 9000
  accessKey: 12345678
  secretKey: qwertyui
  secure: false
  retry:
    times: 4
    pause: 5s
    timeout: 5s
  location: eu-central-1
  prefix: http://localhost:9000
mongo:
  use: false
  host: localhost
  port: 27017
  retry:
    times: 4
    pause: 5s
    timeout: 10s
redis:
  use: false
  host: localhost
  port: 6379
  retry:
    times: 4
    pause: 5s
  expiration: 1h
