name: extra tests
on:
  schedule:
    - cron:  "0 4 * * *"
jobs:
  loadtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - run: make prod-up
      - run: sleep 5 && make loadtest
      - run: make prod-down
